---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
data:
  config.js: |
    window.env = {}
    window.env.API_URL='{{ (default (print "yo-backend." .Release.Namespace ".jenkins-x-example.dev.launch.adobe.net")) .Values.api_url }}'

